export const FETCH_COURSES_DATA_REQUEST = 'FETCH_COURSES_DATA_REQUEST';
export const FETCH_COURSES_DATA_SUCCESS = 'FETCH_COURSES_DATA_SUCCESS';
export const FETCH_COURSES_DATA_FAILURE = 'FETCH_COURSES_DATA_FAILURE';
export const UPDATE_CURRENT_PAGE = 'UPDATE_CURRENT_PAGE';
