export const FETCH_INSTRUCTOR_DATA_REQUEST = 'FETCH_INSTRUCTOR_DATA_REQUEST';
export const FETCH_INSTRUCTOR_DATA_SUCCESS = 'FETCH_INSTRUCTOR_DATA_SUCCESS';
export const FETCH_INSTRUCTOR_DATA_FAILURE = 'FETCH_INSTRUCTOR_DATA_FAILURE';
export const UPDATE_CURRENT_PAGE = 'UPDATE_CURRENT_PAGE';

export const FETCH_CCX_LIST_REQUEST = 'FETCH_CCX_LIST_REQUEST';
export const FETCH_CCX_LIST_SUCCESS = 'FETCH_CCX_LIST_SUCCESS';
export const FETCH_CCX_LIST_FAILURE = 'FETCH_CCX_LIST_FAILURE';

export const FETCH_COURSES_DATA_REQUEST = 'FETCH_COURSES_DATA_REQUEST';
export const FETCH_COURSES_DATA_SUCCESS = 'FETCH_COURSES_DATA_SUCCESS';
export const FETCH_COURSES_DATA_FAILURE = 'FETCH_COURSES_DATA_FAILURE';
