export const FETCH_STUDENTS_DATA_REQUEST = 'FETCH_STUDENTS_DATA_REQUEST';
export const FETCH_STUDENTS_DATA_SUCCESS = 'FETCH_STUDENTS_DATA_SUCCESS';
export const FETCH_STUDENTS_DATA_FAILURE = 'FETCH_STUDENTS_DATA_FAILURE';

export const FETCH_COURSES_DATA_REQUEST = 'FETCH_COURSES_DATA_REQUEST';
export const FETCH_COURSES_DATA_SUCCESS = 'FETCH_COURSES_DATA_SUCCESS';
export const FETCH_COURSES_DATA_FAILURE = 'FETCH_COURSES_DATA_FAILURE';

export const FETCH_CLASSES_DATA_REQUEST = 'FETCH_CLASSES_DATA_REQUEST';
export const FETCH_CLASSES_DATA_SUCCESS = 'FETCH_CLASSES_DATA_SUCCESS';
export const FETCH_CLASSES_DATA_FAILURE = 'FETCH_CLASSES_DATA_FAILURE';

export const FETCH_METRICS_DATA_REQUEST = 'FETCH_METRICS_DATA_REQUEST';
export const FETCH_METRICS_DATA_SUCCESS = 'FETCH_METRICS_DATA_SUCCESS';
export const FETCH_METRICS_DATA_FAILURE = 'FETCH_METRICS_DATA_FAILURE';

export const UPDATE_CURRENT_PAGE = 'UPDATE_CURRENT_PAGE';
