export const FETCH_INSTITUTION_DATA_REQUEST = 'FETCH_INSTITUTION_DATA_REQUEST';
export const FETCH_INSTITUTION_DATA_SUCCESS = 'FETCH_INSTITUTION_DATA_SUCCESS';
export const FETCH_INSTITUTION_DATA_FAILURE = 'FETCH_INSTITUTION_DATA_FAILURE';
